### ISSUE TITLE
Windows Test Failures

### ISSUE THREAD

**Issue by gmkll** [fabriceci/RichFilemanager-JAVA#1]
on windows I get test failures
 (1) cp1252 is the default encoding. Fix could be done in build.gradle
`tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}`
(2) ` at com.fabriceci.fmc.impl.LocalFileManagerTest.actionAddFolderTest(LocalFileManagerTest.java:254)`
actionDeleteTest:
`java.lang.UnsupportedOperationException: 'posix:permissions' not supported as initial attribute
	at sun.nio.fs.WindowsSecurityDescriptor.fromAttribute(WindowsSecurityDescriptor.java:358)
	at sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:492)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at com.fabriceci.fmc.impl.LocalFileManager.getThumbnailDir(LocalFileManager.java:431)`
actionGetFileTest:
`java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/work/git-repo/RichFilemanager-JAVA/build/resources/main/test/result/getFileTxt.json
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at com.fabriceci.fmc.impl.LocalFileManagerTest.actionGetFileTest(LocalFileManagerTest.java:155)`

I could later create a patch (might take some time).

**Comment by fabriceci** [comment]
should be fixed by 3680975073352d3e03931f0a537bccca4096eb54
